### ISSUE TITLE
Generic count including different word variant

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#33]
Generic count including different word variant.

Change translations:
- [x] charts.flag - should have generic options for different amounts: 0 flag, 1 flaga, 2 flagi, 5 flag (in PL)
- [x] filter.readable.flags.suffix=flag, - above keyword can be used-
- [x] notices.count - generic count as above
- [x] `filter.email.afterCount` - generic count needed
- [x] `organizations.count` - gneric count
- [x] `organizations.wins` - generic count

@juzraai How to do it? There should be some java lib to handle it

**Comment by juzraai** [comment]
The search term for this issue was "plural forms i18n" and luckily there's a library called ICU4J which contains (among many other things) the plural rules for each language and can select the proper form for a given numeric value.

I wired this magic in, it works now. Please see the updated documentation:

:point_right: http://docs.redflags.eu/developer/webapp/basic/#plural-forms

Polish language has 4 plural forms: few, many, one and other, so you need to create these 4 variations for every message mentioned above and in the documentation section. For example:

`charts.flag.few=`
`charts.flag.many=`
`charts.flag.one=`
`charts.flag.other=`
