### ISSUE TITLE
Translate interface to Poland

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#7]
- [ ] Translate all the strings

@juzraai is there a translation file?

**Comment by juzraai** [comment]
@KrzysztofMadejski of course, here: https://github.com/petabyte-research/redflags/blob/master/redflags-web/src/main/resources/ - see `messages_LANG.properties` files.

I've just written a cookbook chapter for adding a new language:
http://docs.redflags.eu/developer/cookbook/#adding-a-new-language-to-the-webapp

**Comment by KrzysztofMadejski** [comment]
I'm wondering about `When you are sure you won't need for example IndicatorX gear, you don't have to translate and can remove all message lines which contain IndicatorX.` and the fact that the message keys don't have language key.

I foresee that we may reuse the code of your indicators in Poland (and name them the same), because they will have very simillar functionality, but there may be differences in legal framework, thus a bit different message will be needed.

Then message keys should be prefixed with the language, ie. `flag.hu.CountOfInvOpsNoCondIndicator.desc` and then we may reuse it in `flag.pl.CountOfInvOpsNoCondIndicator.desc` or skip it in the translation files..

@juzraai What do you think?

**Comment by juzraai** [comment]
@KrzysztofMadejski  Well, I agree. 
- This way language files can be extended instead of losing information (overwriting/deleting lines of current Hungarian indicators).
- Though the possibility of differencing indicators by language/country is already existing (classname), it would be more rational to difference them inside language files too (and istead of in the classname), as they are also separated in the package structure (`...gear.indicator.hu`).

These message keys are generated and used automatically at many points inside the system, so I have to think over exactly where/how do I have to refactor the code. Then the documentation must be updated. 

And also I will have to introduce this change to the current live system behind http://redflags.hu/ .

**Comment by juzraai** [comment]
Okay, I've refactored the code and updated the docs as well. The most important part:

The indicator identifier is generated from the **name of the direct parent package** and the **simple class name**, e.g. `hu.petabyte.redflags.engine.gear.indicator.pl.CountOfInvOpsNoCondIndicator` will have `pl.CountOfInvOpsNoCondIndicator` as its id, so its message keys will have the prefix `flag.pl.CountOfInvOpsNoCondIndicator.*`.

**Comment by KrzysztofMadejski** [comment]
Amazing!

**Comment by KrzysztofMadejski** [comment]
Missing translations:
- [x] With the financial support of the Prevention of and Fight against Crime Programme 
  European Commission - Directorate-General Home Affairs
- [x] Read the summary of the project!
- [x] This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. -> Uznanie autorstwa-Na tych samych warunkach 4.0 Międzynarodowe

Other:
- [x] `notice.tedlink` - rename to "check in source" + poprawić link do BZP

**Comment by KrzysztofMadejski** [comment]
https://github.com/epforgpl/redflags/commit/499b231fc311b0e4e492f302b5f86b36c3b027c2

**Comment by KrzysztofMadejski** [comment]
@juzraai FYI I've changed `notice.tedlink` to `notice.checkSource` so it will be valid for all notice sources. -> https://github.com/epforgpl/redflags/commit/90b20f46090dd7073d976a4b4a77ef740085a9b1
